### PR TITLE
Updated JSON file

### PR DESCRIPTION
**Pull request by MonaliProtoTech**
Added ProtoTech as the keyword in Product Name.

### CODE REVIEW

**Comment by MonaliProtoTech** [comment]
Added ProtoTech Keyword.

**Comment by javagl** [comment]
Did you close this intentionally? If not (i.e. if you reopen it), I'd merge it ASAP.

**Comment by MonaliProtoTech** [comment]
No, I haven't close it intentionally. Yes, today I reopen it  and added 
modification in Product name. Added ProtoTech key word in product name 
to easily find all our products with single key word. Below is modified 
script.

{
   "name" : "ProtoTech's glTF Exporter For Inventor",
   "description" : "Export Inventor model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/inventor/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "ProtoTech's glTF Exporter For Fusion 360",
   "description" : "Export Fusion 360 model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/fusion-360/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "ProtoTech's glTF Exporter For Revit",
   "description" : "Export Revit design to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/revit/gltf-exporter/",
    "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "ProtoTech's glTF Exporter For SolidEdge",
   "description" : "Export SolidEdge model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/solidedge/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
  }, {
   "name" : "ProtoTech's glTF Exporter For SolidWorks",
   "description" : "Export Solidworks model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/solidworks/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}

Regards,

*_________________________________
Monali Thete*
Team Lead
Tel (Office): 020-67117117
ProtoTech Solutions & Services Pvt. Ltd.
www.ProtoTechSolutions.com <https://www.prototechsolutions.com>

/DISCLAIMER: This e-mail may contain privileged and confidential 
information which is the property of ProtoTech Solutions. It is intended 
only for the use of the individual or entity to which it is addressed. 
If you are not the intended recipient, you are not authorized to read, 
retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and 
delete all copies of this message. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be 
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or 
contain viruses. The sender therefore does not accept liability for any 
errors or omissions in the contents or attachments (if any) of this 
message, which arise as a result of e-mail transmission./

**Comment by MonaliProtoTech** [comment]
Thank you for quick response and update.

Regards,

*_________________________________
Monali Thete*
Team Lead
Tel (Office): 020-67117117
ProtoTech Solutions & Services Pvt. Ltd.
www.ProtoTechSolutions.com <https://www.prototechsolutions.com>

/DISCLAIMER: This e-mail may contain privileged and confidential 
information which is the property of ProtoTech Solutions. It is intended 
only for the use of the individual or entity to which it is addressed. 
If you are not the intended recipient, you are not authorized to read, 
retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and 
delete all copies of this message. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be 
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or 
contain viruses. The sender therefore does not accept liability for any 
errors or omissions in the contents or attachments (if any) of this 
message, which arise as a result of e-mail transmission./

**Pull request merged**
