### PR TITLE
Update glTF-projects-data.json

### PR DESCRIPTION
**Pull request by MonaliProtoTech**
Prototech GLTF exporters.

### CODE REVIEW

**Comment by MonaliProtoTech** [comment]
Prototech GLTF Exporters.

**Comment by MonaliProtoTech** [comment]
ProtoTech GLTF Exporters for different CAD platforms.

**Comment by javagl** [comment]
Thanks for your contribution.

There had been (a merge conflict with another PR, but more importantly) some formatting errors in the JSON, e.g. missing `"quotation marks"` around links and such. 

So I have added the projects manually in another PR, namely https://github.com/KhronosGroup/glTF-Project-Explorer/pull/57 , and also merged it, and the update should be visible on the project explorer page soon.

**Comment by MonaliProtoTech** [comment]
Hi Marco,

Any update on this? Still I can not see the projects submitted by me in  
GLTF Project Explorer. Anything need to be done from my end.

Regards,

*_________________________________
Monali Thete*
Team Lead
Tel (Office): 020-67117117
ProtoTech Solutions & Services Pvt. Ltd.
www.ProtoTechSolutions.com <https://www.prototechsolutions.com>

/DISCLAIMER: This e-mail may contain privileged and confidential 
information which is the property of ProtoTech Solutions. It is intended 
only for the use of the individual or entity to which it is addressed. 
If you are not the intended recipient, you are not authorized to read, 
retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and 
delete all copies of this message. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be 
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or 
contain viruses. The sender therefore does not accept liability for any 
errors or omissions in the contents or attachments (if any) of this 
message, which arise as a result of e-mail transmission./

**Comment by javagl** [comment]
The deployment should largely be automated, but indeed, the latest change does not seem to appear yet.

@weegeekps The *previous* change seemed to have become visible in the online version automatically, but the *most recent* one doesn't seem to appear. I think that you once wrote a few hints about the deployment (or how to trigger it manually), but haven't found it right now. If you give me a short hint or pointer, I'd (try to) add some information to a DEPLOYMENT.md or so...

**Comment by MonaliProtoTech** [comment]
Hi Marco, I am not getting what is wrong is the data provided by me.

I want to add below data in json script

  {
   "name" : "glTF Exporter For Inventor",
   "description" : "Export Inventor model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/inventor/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "glTF Exporter For Fusion 360",
   "description" : "Export Fusion 360 model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/fusion-360/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "glTF Exporter For Revit",
   "description" : "Export Revit design to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/revit/gltf-exporter/",
    "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}, {
   "name" : "glTF Exporter For SolidEdge",
   "description" : "Export SolidEdge model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/solidedge/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
  }, {
   "name" : "glTF Exporter For SolidWorks",
   "description" : "Export Solidworks model to GLTF and GLB files",
   "link" : 
"https://prototechsolutions.com/3d-products/solidworks/gltf-exporter/",
   "task" : [ "export" ],
   "type" : [ "plugin", "sdk" ],
   "language" : [ "c#" ],
   "outputs" : [ "glTF 2.0" ]
}


These are products from PrototechSolutions.

Please guide me on further process so our products get added in Project 
Explorer.

*_________________________________
Monali Thete*
Team Lead
Tel (Office): 020-67117117
ProtoTech Solutions & Services Pvt. Ltd.
www.ProtoTechSolutions.com <https://www.prototechsolutions.com>

/DISCLAIMER: This e-mail may contain privileged and confidential 
information which is the property of ProtoTech Solutions. It is intended 
only for the use of the individual or entity to which it is addressed. 
If you are not the intended recipient, you are not authorized to read, 
retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and 
delete all copies of this message. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be 
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or 
contain viruses. The sender therefore does not accept liability for any 
errors or omissions in the contents or attachments (if any) of this 
message, which arise as a result of e-mail transmission./

**Comment by javagl** [comment]
The information has been added with this commit: https://github.com/KhronosGroup/glTF-Project-Explorer/pull/57/commits/f0a8687aacd5fe9f3d62a9dcdb7755022b1c587b 

It *should* be visible on the Project Explorer website soon. I just had to ask @weegeekps to find out what has to be done so that these new entries appear on the website.

**Comment by weegeekps** [comment]
@javagl I see all of the entries added by this PR on the site. I think this is likely a browser caching issue. Can you please try clearing your cache and confirm to me? If it is there is a quick solution we can implement.

**Comment by javagl** [comment]
Indeed, now they appear (but I have to admit that during my previous test, I entered "Protech" into the search bar, and that doesn't appear in the titles... so the issue was either entirely my fault, or due to [caching](https://shouldiblamecaching.com/) ...).

Sorry for bugging you with these notifications.

@MonaliProtoTech The projects should now appear in http://github.khronos.org/glTF-Project-Explorer/ - for example, when searching for `SolidEdge`, it immediately shows your SolidEdge exporter project.

**Pull request closed without merging**
