### PR TITLE
F3D migration

### PR DESCRIPTION
**Pull request by mwestphal**

### CODE REVIEW

**Comment by javagl** [comment]
@weegeekps I had seen this PR and considered to ping you, but ... apparently, you know the answer to the question that I would have asked: "What is this?". (If it's not possible to provide enough context for me in one or two sentences, feel free to ignore that question...)

**Comment by mwestphal** [comment]
Looks like the question is not for me, in any case I should have added some context. I have added to the list of application some time ago and we (f3d devs) migrated the repo and website, so I've just updated it. I hope thats okay.

**Comment by weegeekps** [comment]
No worries. I noticed you had mentioned the PR in your own issue on your repo and figured since you appeared to be the lead contributor for F3D, the site you were switching to was valid, and the change seemed minimal, that no further discussion was required.

@javagl Should I have not merged this PR so willingly? Perhaps we need to come up with some ground rules in the event that a PR author doesn't include much context? In retrospect I realize I probably should have asked a question to the contributor.

**Comment by javagl** [comment]
Sorry, I could have derived the context from the linked f3d-app issue. Of course, in this case, it's perfectly fine to just merge it - no need to establish any other process: When a PR is obviously legitimate, every maintainer can just merge it.

**Pull request merged**
