### PR TITLE
Implemented "Tags" and sorting of results.

### PR DESCRIPTION
**Pull request by weegeekps**
As discussed in #23.

### CODE REVIEW

**Comment by weegeekps** [comment]
FYI. VSCode decided it wanted to reformat the data file when I was modifying it. My apologies.

**Comment by weegeekps** [comment]
No, that's a fine review.

My goal with the approach was to make it simple to follow, stick to idiomatic JS style and native functions, and allowing the approach to sort each chunk asynchronously if needed in the future. I admit I may have over-engineered it a bit given that last point.

That said, thank you for making me realize I can simplify this a bit. Rather than using our own compare function within the sort, we can actually just use `String.prototype.localeCompare`. I also realized I can eliminate the `applySort` function entirely using `map`. I will change this around a bit.

**Comment by weegeekps** [comment]
Ok, take a look at that. A couple notes:

* There is now only one function for the sort within in the saga, the aptly named `sortResults`.
* I kept with the buckets approach since the native sort method in JS is a destructive sort. Splitting the tags into sorted buckets is just simpler to manage rather than dealing with a more complicated comparator.
* The final step is using a `flatMap`, `sort`, and `localeCompare`. Looks much cleaner and `localeCompare` ignores accents by default so more reliable as well.

**Comment by weegeekps** [comment]
No worries, I appreciate the reviews regardless of your experience with the language. It's always helpful and you always have good comments.

FWIW, there are libraries (such as [Ramda](https://ramdajs.com/)) that give us some better tools with which to sort, combine comparators, and other things that we could bring into the project, but they can add a fair bit of extra JavaScript that needs to be downloaded and parsed before the site loads, and I don't think we've reached the point where the value outweighs the cost quite yet.

**Comment by javagl** [comment]
Sure, there are libraries ... for ... *everything*. One of my main difficulties when it comes to getting a grip on JavaScript is that there is no standard or best practice. I mean, for nothing. Not at all. A quick websearch reveals things like https://github.com/stoeffel/awesome-fp-js , and there are literally *hundreds* of resources for the overly specific topic of functional programming in JS. They all have their pros and cons, and I cannot imagine someone claiming to judge which of them is "better" than another, and how many of them only consist of a GitHub repo with the last of 3 commits having been done 5 years ago. 

(This *may* sound like a rant, but I think there are some parallels to the glTF projects list in that regard - and on the linked page, "Ramda" is the first one in the list, so there even is a parallel to this specific PR ;-))

**Comment by javagl** [comment]
On a more technical note: 

- I think that https://github.com/KhronosGroup/glTF-Project-Explorer/issues/23 can be closed now (I'll just do this - when there is demand for refinement or things like the ideas of ~"Using number of GitHub stars for sorting", it can be reopened or brought up as another issue)
- I considered adding information about the `tags` in the list of supported properties in the README. But since the tags are currently only used internally, and should only be added by maintainers, I think it should (intentionally) not be mentioned there.

**Pull request merged**
