### PR TITLE
V2 UI Improvements

### PR DESCRIPTION
**Pull request by weegeekps**
This in-progress PR contains the major UI improvements for V2.

- [x] Migrate to Tailwind CSS.
- [x] Move the filter bar in a desktop layout to the left.

### CODE REVIEW

**Comment by weegeekps** [comment]
@javagl Here's the PR with the latest for the V2 changes. You'll need to run this locally, and your mileage may vary. Please let me know if you find any issues.

**Comment by javagl** [comment]
I probably cannot do a sensible "review" here.

The actual changes here mainly refer to the UI. I had to do a websearch what "tailwind" actually is, but bailed out when I saw that this is just another framework that wraps the unbearable complexity of CSS away (not necessarily into something that is _less complex_, but maybe just complex _in a different way_...). When it comes to style and appearance, I'm more on the ... let's say 'pragmatic' side of things (c.f. https://javagl.github.io/GLConstantsTranslator/GLConstantsTranslator.html ). 

I have seen that there are some structures prepared for the last checkbox, namely for the "Details View", but am not sure about the current state of this. 

I started looking at the code, but also might need a refresher for React in general: For some things, I'm not sure whether this is part of a reviewable design- or implementation choice, or whether they are just "that's how we roll" in React.

However, more on the ""backend""/structural side: 

---
`<brainstorming>`

<sup>I initially wanted to post the following block in https://github.com/KhronosGroup/glTF-Project-Explorer/issues/122 , because it is rather "brainstorming" - but not in terms of _functionality_, but rather in terms of "architecture", so it did not really fit there. I hope it's OK to drop this here...</sup>

I saw that there are a few things that are probably related to https://github.com/KhronosGroup/glTF-Project-Explorer/issues/144, namely, a `fetchExtensions` function in the `DataService.ts`, and `inputExtensions`/`outputExtensions` in the `IProjectInfo`. I think that the `IProjectInfo` is the central place that will have to be reviewed and possibly changed in order to generalize the project explorer as to become an "Ecosystem Explorer". 

The `id`, `name`, `description` and `link` fields are generic enough to be applicable to basically _everything_, so they can probably remain as they are. 

The other fields are already specific for software projects, and maybe even specific for glTF. Some of them have already been part of some discussion - for example, `task` might be changed to `keywords`...

In view of https://github.com/KhronosGroup/glTF-Project-Explorer/issues/88 , there would be entirely different properties - probably something like `author` and `conference` or `publisher` (nah, not all the possible BibTex properties, but maybe _some_ of them...). 

Now, the specific properties are currently "linked" to the UI part - throughout the code, without any abstraction: Starting at the `IProjectInfo`, they also appear in `IUpdateFiltersAction`, various functions, down to the `tailwind.config.js`, where the background color of one button is stored via `{ theme: { extend: { colors: { filter: { task: "#ffdac1", ... } } } } ...`. This makes it difficult to generalize anything, and every change (even just renaming `task` to `keyword`) would affect every part of the code (and I don't know how someone should find that tailwind config entry - it took me a while to figure out where this color comes from...). 

I'm not sure about the possibilities or "best practices" for generalizing the UI-specific part, but maybe that can be decided later. Starting from the "modeling side", one could imagine structures like these:
```
interface IProjectInfo {
  id: number;
  name: string;
  description?: string;
  link?: string;
}
interface ISoftwareProjectInfo extends IProjectInfo {
  license?: ProjectLicense[];
  type?: ProjectType[];
  language?: ProjectLanguage[];
}
interface IArticleProjectInfo extends IProjectInfo {
  authors?: string[];
  publisher?: string[];
  language?: string[]; // Not the programming language here, of course :-) 
  ...
}
// Maybe even an "IGltfSoftwareProjectInfo extends ISoftwareProjectInfo"...
```
These properties could, **very** roughly speaking, correspond to the "database schema columns". Then, it would be necessary to be able to access these properties _programmatically_ (and not with `instanceof`). I thought that it would be great to have something that describes the structure of entries similar to a JSON schema:
```
"entryStructure": {
    "name": { 
        "type": "string",
        "description": "The name of the project that will be displayed in the title"
     }
    "description": { 
        "type": "string",
        "description": "The description that will appear in the detail view"
     },
     ...
     "inputs": { 
        "type": "string[]",
        "description": "An array of strings that are the file extensions of input file formats"
     },
}
```
and basically make the `IProjectInfo` generic enough to be able to define the structure of an `IProjectInfo` with such a file. (And ... maybe this file could also have a `"backgroundColorForTagFilterButton": "0xCAFEBABE"` for each entry...)

One could probably make some simplifying assumptions for mapping this to the UI. For example, one could require that each property is just represented as an array of strings. Even if it is something like a `publicationYear` for an "Article": Modeling this as a `string[1]` looks quirky, but far less than trying to encode and process(!) arbitrary type information generically.

`</brainstorming>`

---

A few things that could actually be part of a "code review":

- There are not nearly enough comments in the code
- `FilterActionTypes.PERFORM_SEARCH` is not used
- `IUpdateSelectedFiltersAction` and related elements are not used

(but maybe these are due to the 'draft' state)

**Comment by weegeekps** [comment]
@javagl As discussed, I've moved the detail screen and extensions work into a branch and cleaned this one up so we can merge it. Please take a look and let me know if you have any questions.

**Comment by javagl** [comment]
I had a look at the updated state (i.e. the changes), but as I mentioned above, I'd need to dive deeper into React in order to be able to identify any issues here (beyond the high-level ones, like 'There are no comments'). However, I started the updated state locally, and tried it out, including wild clicking and filtering and changing the window size (c.f. `useWindowDimensions`), and everything seems to work as it should.

OK for me to merge this. I'll carve out some of the 'brainstorming' above into a dedicated issue.

**Comment by weegeekps** [comment]
Thanks, @javagl. I am going to go ahead and merge this into the repo now.

**Pull request merged**
